### ISSUE TITLE
How to predict(infer) on my own sentences(bag-level)?

### ISSUE THREAD

**Issue by KennyNg-19** [GDAMining/gda-extraction#1]
I am using it to do distant supervised learning on Biorel. After training, I try to use the model in ckpt file to predict on new biomedical sentences in bag level.

I am using it with the CNNEncoder encoder and the BagCNNAttention model 

```
rel2id = json.load(open(os.path.join(root_path, 'benchmark/biorel/biorel_rel2id.json')))

word2id = json.load(open(os.path.join(root_path, 'pretrain/biowordvec', dataset, 'biowordvec_word2id.json')))
word2vec = np.load(os.path.join(root_path, 'pretrain/biowordvec', dataset, 'biowordvec_mat.npy'))

sentence_encoder = opennre.encoder.CNNEncoder(
    token2id=word2id,
    max_length=100,
    word_size=200,
    position_size=10,
    hidden_size=250,
    blank_padding=True,
    kernel_size=3,
    padding_size=1,
    word2vec=word2vec,
    dropout=0.5
)

model = opennre.model.BagCNNAttention(sentence_encoder, len(rel2id), rel2id)

model_name = 'biorel_cnn_att'
ckpt = os.path.join('./', 'ckpt/' + model_name + '.pth.tar')

model.load_state_dict(torch.load(ckpt, map_location='cpu')['state_dict'])

```

However, I make a input bags of sentences, 

```
input = [{
    "text": "treatment of severe symptomatic trichuriasis observed with heavy worm burdens is not satisfactory with recommended doses of mebendazole , flubendazole and albendazole .", 
    "h": {"pos": [43, 69]}, 
    "t": {"pos": [155, 166]}
    },
    {"text": "treatment of severe symptomatic trichuriasis observed with heavy worm burdens is not satisfactory with recommended doses of mebendazole , flubendazole and albendazole .", 
    "h": {"pos": [43, 69]}, 
    "t": {"pos": [155, 166]}
    }]
         
model.infer(input)
```
But the error says, 

```
~/opt/anaconda3/envs/opennre2/lib/python3.6/site-packages/gda_extraction-0.1-py3.6.egg/opennre/model/bag_average.py in infer(self, bag)
     47         masks = []
     48         for item in bag:
---> 49             token, pos1, pos2, mask = self.sentence_encoder.tokenize(item)
     50             tokens.append(token)
     51             pos1s.append(pos1)

ValueError: not enough values to unpack (expected 4, got 3)
```

Which means, the CNNEncoder(BaseEncoder) doesn't return a **mask**  when tokenizing text input but the OpenNRE is exactly using the CNNEncoder when building a BagCNNAverage model.

How to solve this? I think maybe there is sth I missed?

**Comment by stefano-marchesin** [comment]
Hi, 

the model.infer(input) function comes from the OpenNRE package and it does not work -- at least not in the version I worked with. I suggest you treat your new sentences as a unique 'test' file (or as different ones), and thus use the 'test_loader' function you can find in all the  'train_###.py' files. My guess, but I am not sure, is that the model.infer(input) is deprecated and no longer used within OpenNRE. However, I never used it in my experiments, so I never looked at it! Given this is part of the OpenNRE library, I suggest you write to the authors of the OpenNRE GitHub repo directly (link: https://github.com/thunlp/OpenNRE). If you find a solution to this, let me know and I will update the corresponding code also here!

Cheers,
Stefano

**Comment by KennyNg-19** [comment]
> Hi,
> 
> the model.infer(input) function comes from the OpenNRE package and it does not work -- at least not in the version I worked with. I suggest you treat your new sentences as a unique 'test' file (or as different ones), and thus use the 'test_loader' function you can find in all the 'train_###.py' files. My guess, but I am not sure, is that the model.infer(input) is deprecated and no longer used within OpenNRE. However, I never used it in my experiments, so I never looked at it! Given this is part of the OpenNRE library, I suggest you write to the authors of the OpenNRE GitHub repo directly (link: https://github.com/thunlp/OpenNRE). If you find a solution to this, let me know and I will update the corresponding code also here!
> 
> Cheers,
> Stefano

Hi, thanks for the reply. I also find there is a missing file "pretraine.py" in /opennre after installing OpenNRE package to your instructions. Could you try the whole install instructions to see if it is the case?

```
  File "/Users/kenny/opt/anaconda3/envs/pytorch/lib/python3.6/site-packages/gda_extraction-0.1-py3.6.egg/opennre/__init__.py", line 5, in <module>
ModuleNotFoundError: No module named 'opennre.pretrain'
```

**Comment by stefano-marchesin** [comment]
Hi, 

I do not have this kind of problem by working with the cloned version of my repo. I just tried to create a new conda env and re-installing everything and had no problems with it. That's probably a file related to a different version of OpenNRE. The gda-extraction repository has been tested with the version of OpenNRE that you can find here, there are no guarantees with different versions. 

Therefore, if you try to use gda-extraction w/ different OpenNRE versions you might incur into some differences. 

Cheers, 
Stefano
